#!/bin/bash

crt=${1}
key=${2}
csr=${3}

[[ -f ${crt} ]] && m_crt=$(openssl x509 -noout -modulus -in ${crt} | openssl md5)
[[ -f ${key} ]] && m_key=$(openssl rsa  -noout -modulus -in ${key} | openssl md5)
[[ -f ${csr} ]] && m_csr=$(openssl req  -noout -modulus -in ${csr} | openssl md5)

echo "Certificate Modulus: ${m_crt}"
echo "Key Modulus        : ${m_key}"
echo "CSR Modulus        : ${m_csr}"

[[ ${m_crt} == ${m_key} ]]
